stages:
#    - build
    - deploy

#build_node:
#    stage: build
#    rules:
#        - if: '$CI_COMMIT_BRANCH =~ /^(production|test)$/'
#    image: node:18.15.0
#    script:
#        - npm i
#        - npm run build
#    tags:
#        - deploy

deploy:
    image: ubuntu:latest
    environment: $CI_COMMIT_BRANCH
    stage: deploy
    rules:
        -   if: '$CI_COMMIT_BRANCH =~ /^(production|test)$/'
    tags:
        - deploy
    before_script:
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - echo "$SSH_KEY"
        - echo "$PROJECT_PATH"
        - ssh-add <(echo "$SSH_KEY" | base64 -d)
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "end before script"
    script:
        - ssh $SSH_USER@$HOST "cd $PROJECT_PATH && git checkout $CI_COMMIT_BRANCH && git pull origin $CI_COMMIT_BRANCH && exit"
