stages:
    - build
    - deploy

build_node:
    stage: build
    rules:
        - if: '$CI_COMMIT_BRANCH =~ /^(production|test)$/'
    image: node:18.15.0
    script:
        - npm i
        - npm run build
    tags:
        - deploy

deploy:
    image: alpine:latest
    environment: $CI_COMMIT_BRANCH
    stage: deploy
    rules:
        -   if: '$CI_COMMIT_BRANCH =~ /^(production|test)$/'
    tags:
        - deploy
    before_script:
        - echo "$SSH_KEY"
        - echo "$SSH_USER"
        - echo "$HOST"
        - echo "$PROJECT_PATH"
        - apk add openssh-client
        - eval $(ssh-agent -s)
        - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
    script:
        - ssh -o StrictHostKeyChecking=no $SSH_USER@$HOST "cd $PROJECT_PATH && git pull && exit"
