stages:
    - build
    - deploy

build_node:
    stage: build
    rules:
        - if: '$CI_COMMIT_BRANCH =~ /^(production|test)$/'
    image: node:18.15.0
    script:
        - npm i
        - npm run build
    tags:
        - deploy

deploy:
    image: ubuntu:latest
    environment: $CI_COMMIT_BRANCH
    stage: deploy
    rules:
        -   if: '$CI_COMMIT_BRANCH =~ /^(production|test)$/'
    tags:
        - deploy
    before_script:
        - apt-get -yq update
        - apt-get -yqq install ssh
        - install -m 600 -D /dev/null ~/.ssh/id_rsa
        - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
        - ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
    script:
        - ssh $SSH_USER@$HOST "cd $PROJECT_PATH && git checkout $CI_COMMIT_BRANCH && git pull && exit"
