stages:
#    - build
    - deploy

#build_node:
#    stage: build
#    rules:
#        - if: '$CI_COMMIT_BRANCH =~ /^(production|test)$/'
#    image: node:18.15.0
#    script:
#        - npm i
#        - npm run build
#    tags:
#        - deploy

deploy:
    image: ubuntu:latest
    environment: $CI_COMMIT_BRANCH
    stage: deploy
    rules:
        -   if: '$CI_COMMIT_BRANCH =~ /^(production|test)$/'
    tags:
        - deploy
    before_script:
        - echo "end before script"git
        - echo "$CI_COMMIT_BRANCH"
        - echo "$HOST"
    script:
        - echo "end script"
